/* tslint:disable */
/* eslint-disable */
/**
 * Token Metadata Gateway
 * Token metadata lookup by chain (CAIP-2) and contract address. Caches in KV on first lookup. Sources: CoinGecko API → on-chain ERC20 eth_call → Trust Wallet assets for logo. Logo images served via gateway proxy (no external CDN access needed).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1TokensChainContractAddressGet200Response,
} from '../models/index';
import {
    ApiV1TokensChainContractAddressGet200ResponseFromJSON,
    ApiV1TokensChainContractAddressGet200ResponseToJSON,
} from '../models/index';

export interface ApiV1TokensChainContractAddressGetRequest {
    chain: string;
    contractAddress: string;
    force?: ApiV1TokensChainContractAddressGetForceEnum;
}

export interface ApiV1TokensChainContractAddressLogoGetRequest {
    chain: string;
    contractAddress: string;
}

/**
 * TokensApi - interface
 * 
 * @export
 * @interface TokensApiInterface
 */
export interface TokensApiInterface {
    /**
     * Creates request options for apiV1TokensChainContractAddressGet without sending the request
     * @param {string} chain 
     * @param {string} contractAddress 
     * @param {'true'} [force] Skip cache and force refresh from external sources
     * @throws {RequiredError}
     * @memberof TokensApiInterface
     */
    apiV1TokensChainContractAddressGetRequestOpts(requestParameters: ApiV1TokensChainContractAddressGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Fetch metadata for a specific token by chain and contract address. On first lookup, sources from CoinGecko → on-chain RPC eth_call. Supports ?force=true to skip cache and refresh from external sources.
     * @summary Get token metadata
     * @param {string} chain 
     * @param {string} contractAddress 
     * @param {'true'} [force] Skip cache and force refresh from external sources
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokensApiInterface
     */
    apiV1TokensChainContractAddressGetRaw(requestParameters: ApiV1TokensChainContractAddressGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1TokensChainContractAddressGet200Response>>;

    /**
     * Fetch metadata for a specific token by chain and contract address. On first lookup, sources from CoinGecko → on-chain RPC eth_call. Supports ?force=true to skip cache and refresh from external sources.
     * Get token metadata
     */
    apiV1TokensChainContractAddressGet(requestParameters: ApiV1TokensChainContractAddressGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1TokensChainContractAddressGet200Response>;

    /**
     * Creates request options for apiV1TokensChainContractAddressLogoGet without sending the request
     * @param {string} chain 
     * @param {string} contractAddress 
     * @throws {RequiredError}
     * @memberof TokensApiInterface
     */
    apiV1TokensChainContractAddressLogoGetRequestOpts(requestParameters: ApiV1TokensChainContractAddressLogoGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Proxy token logo image from external CDN (CoinGecko or Trust Wallet). Returns the image bytes directly with edge caching.
     * @summary Get token logo
     * @param {string} chain 
     * @param {string} contractAddress 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokensApiInterface
     */
    apiV1TokensChainContractAddressLogoGetRaw(requestParameters: ApiV1TokensChainContractAddressLogoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     * Proxy token logo image from external CDN (CoinGecko or Trust Wallet). Returns the image bytes directly with edge caching.
     * Get token logo
     */
    apiV1TokensChainContractAddressLogoGet(requestParameters: ApiV1TokensChainContractAddressLogoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

}

/**
 * 
 */
export class TokensApi extends runtime.BaseAPI implements TokensApiInterface {

    /**
     * Creates request options for apiV1TokensChainContractAddressGet without sending the request
     */
    async apiV1TokensChainContractAddressGetRequestOpts(requestParameters: ApiV1TokensChainContractAddressGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling apiV1TokensChainContractAddressGet().'
            );
        }

        if (requestParameters['contractAddress'] == null) {
            throw new runtime.RequiredError(
                'contractAddress',
                'Required parameter "contractAddress" was null or undefined when calling apiV1TokensChainContractAddressGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['force'] != null) {
            queryParameters['force'] = requestParameters['force'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tokens/{chain}/{contractAddress}`;
        urlPath = urlPath.replace(`{${"chain"}}`, encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace(`{${"contractAddress"}}`, encodeURIComponent(String(requestParameters['contractAddress'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch metadata for a specific token by chain and contract address. On first lookup, sources from CoinGecko → on-chain RPC eth_call. Supports ?force=true to skip cache and refresh from external sources.
     * Get token metadata
     */
    async apiV1TokensChainContractAddressGetRaw(requestParameters: ApiV1TokensChainContractAddressGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1TokensChainContractAddressGet200Response>> {
        const requestOptions = await this.apiV1TokensChainContractAddressGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1TokensChainContractAddressGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Fetch metadata for a specific token by chain and contract address. On first lookup, sources from CoinGecko → on-chain RPC eth_call. Supports ?force=true to skip cache and refresh from external sources.
     * Get token metadata
     */
    async apiV1TokensChainContractAddressGet(requestParameters: ApiV1TokensChainContractAddressGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1TokensChainContractAddressGet200Response> {
        const response = await this.apiV1TokensChainContractAddressGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiV1TokensChainContractAddressLogoGet without sending the request
     */
    async apiV1TokensChainContractAddressLogoGetRequestOpts(requestParameters: ApiV1TokensChainContractAddressLogoGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chain'] == null) {
            throw new runtime.RequiredError(
                'chain',
                'Required parameter "chain" was null or undefined when calling apiV1TokensChainContractAddressLogoGet().'
            );
        }

        if (requestParameters['contractAddress'] == null) {
            throw new runtime.RequiredError(
                'contractAddress',
                'Required parameter "contractAddress" was null or undefined when calling apiV1TokensChainContractAddressLogoGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tokens/{chain}/{contractAddress}/logo`;
        urlPath = urlPath.replace(`{${"chain"}}`, encodeURIComponent(String(requestParameters['chain'])));
        urlPath = urlPath.replace(`{${"contractAddress"}}`, encodeURIComponent(String(requestParameters['contractAddress'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Proxy token logo image from external CDN (CoinGecko or Trust Wallet). Returns the image bytes directly with edge caching.
     * Get token logo
     */
    async apiV1TokensChainContractAddressLogoGetRaw(requestParameters: ApiV1TokensChainContractAddressLogoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.apiV1TokensChainContractAddressLogoGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Proxy token logo image from external CDN (CoinGecko or Trust Wallet). Returns the image bytes directly with edge caching.
     * Get token logo
     */
    async apiV1TokensChainContractAddressLogoGet(requestParameters: ApiV1TokensChainContractAddressLogoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.apiV1TokensChainContractAddressLogoGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiV1TokensChainContractAddressGetForceEnum = {
    True: 'true'
} as const;
export type ApiV1TokensChainContractAddressGetForceEnum = typeof ApiV1TokensChainContractAddressGetForceEnum[keyof typeof ApiV1TokensChainContractAddressGetForceEnum];
