/* tslint:disable */
/* eslint-disable */
/**
 * Token Metadata Gateway
 * Token metadata lookup by chain (CAIP-2) and contract address. Caches in KV on first lookup. Sources: CoinGecko API → on-chain ERC20 eth_call → Trust Wallet assets for logo. Logo images served via gateway proxy (no external CDN access needed).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { TokenMeta } from './TokenMeta';
import {
    TokenMetaFromJSON,
    TokenMetaFromJSONTyped,
    TokenMetaToJSON,
    TokenMetaToJSONTyped,
} from './TokenMeta';

/**
 * 
 * @export
 * @interface ApiV1TokensChainListGet200Response
 */
export interface ApiV1TokensChainListGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1TokensChainListGet200Response
     */
    success?: boolean;
    /**
     * 
     * @type {Array<TokenMeta>}
     * @memberof ApiV1TokensChainListGet200Response
     */
    data?: Array<TokenMeta>;
    /**
     * 
     * @type {Pagination}
     * @memberof ApiV1TokensChainListGet200Response
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the ApiV1TokensChainListGet200Response interface.
 */
export function instanceOfApiV1TokensChainListGet200Response(value: object): value is ApiV1TokensChainListGet200Response {
    return true;
}

export function ApiV1TokensChainListGet200ResponseFromJSON(json: any): ApiV1TokensChainListGet200Response {
    return ApiV1TokensChainListGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1TokensChainListGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1TokensChainListGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TokenMetaFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function ApiV1TokensChainListGet200ResponseToJSON(json: any): ApiV1TokensChainListGet200Response {
    return ApiV1TokensChainListGet200ResponseToJSONTyped(json, false);
}

export function ApiV1TokensChainListGet200ResponseToJSONTyped(value?: ApiV1TokensChainListGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TokenMetaToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

