/* tslint:disable */
/* eslint-disable */
/**
 * Token Metadata Gateway
 * Token metadata lookup by chain (CAIP-2) and contract address. Caches in KV on first lookup. Sources: CoinGecko API → on-chain ERC20 eth_call → Trust Wallet assets for logo. Logo images served via gateway proxy (no external CDN access needed).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenMeta } from './TokenMeta';
import {
    TokenMetaFromJSON,
    TokenMetaFromJSONTyped,
    TokenMetaToJSON,
    TokenMetaToJSONTyped,
} from './TokenMeta';

/**
 * 
 * @export
 * @interface ApiV1TokensChainContractAddressGet200Response
 */
export interface ApiV1TokensChainContractAddressGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1TokensChainContractAddressGet200Response
     */
    success?: boolean;
    /**
     * 
     * @type {TokenMeta}
     * @memberof ApiV1TokensChainContractAddressGet200Response
     */
    data?: TokenMeta;
}

/**
 * Check if a given object implements the ApiV1TokensChainContractAddressGet200Response interface.
 */
export function instanceOfApiV1TokensChainContractAddressGet200Response(value: object): value is ApiV1TokensChainContractAddressGet200Response {
    return true;
}

export function ApiV1TokensChainContractAddressGet200ResponseFromJSON(json: any): ApiV1TokensChainContractAddressGet200Response {
    return ApiV1TokensChainContractAddressGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1TokensChainContractAddressGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1TokensChainContractAddressGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : TokenMetaFromJSON(json['data']),
    };
}

export function ApiV1TokensChainContractAddressGet200ResponseToJSON(json: any): ApiV1TokensChainContractAddressGet200Response {
    return ApiV1TokensChainContractAddressGet200ResponseToJSONTyped(json, false);
}

export function ApiV1TokensChainContractAddressGet200ResponseToJSONTyped(value?: ApiV1TokensChainContractAddressGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': TokenMetaToJSON(value['data']),
    };
}

