/* tslint:disable */
/* eslint-disable */
/**
 * Token Metadata Gateway
 * Token metadata lookup by chain (CAIP-2) and contract address. Caches in KV on first lookup. Sources: CoinGecko API → on-chain ERC20 eth_call → Trust Wallet assets for logo. Logo images served via gateway proxy (no external CDN access needed).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1TokensChainBatchPostRequest
 */
export interface ApiV1TokensChainBatchPostRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1TokensChainBatchPostRequest
     */
    addresses?: Array<string>;
}

/**
 * Check if a given object implements the ApiV1TokensChainBatchPostRequest interface.
 */
export function instanceOfApiV1TokensChainBatchPostRequest(value: object): value is ApiV1TokensChainBatchPostRequest {
    return true;
}

export function ApiV1TokensChainBatchPostRequestFromJSON(json: any): ApiV1TokensChainBatchPostRequest {
    return ApiV1TokensChainBatchPostRequestFromJSONTyped(json, false);
}

export function ApiV1TokensChainBatchPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1TokensChainBatchPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'addresses': json['addresses'] == null ? undefined : json['addresses'],
    };
}

export function ApiV1TokensChainBatchPostRequestToJSON(json: any): ApiV1TokensChainBatchPostRequest {
    return ApiV1TokensChainBatchPostRequestToJSONTyped(json, false);
}

export function ApiV1TokensChainBatchPostRequestToJSONTyped(value?: ApiV1TokensChainBatchPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addresses': value['addresses'],
    };
}

