/* tslint:disable */
/* eslint-disable */
/**
 * Token Metadata Gateway
 * Token metadata lookup by chain (CAIP-2) and contract address. Caches in KV on first lookup. Sources: CoinGecko API → on-chain ERC20 eth_call → Trust Wallet assets for logo. Logo images served via gateway proxy (no external CDN access needed).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthGet200Response
 */
export interface HealthGet200Response {
    /**
     * 
     * @type {string}
     * @memberof HealthGet200Response
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof HealthGet200Response
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof HealthGet200Response
     */
    version?: string;
}

/**
 * Check if a given object implements the HealthGet200Response interface.
 */
export function instanceOfHealthGet200Response(value: object): value is HealthGet200Response {
    return true;
}

export function HealthGet200ResponseFromJSON(json: any): HealthGet200Response {
    return HealthGet200ResponseFromJSONTyped(json, false);
}

export function HealthGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function HealthGet200ResponseToJSON(json: any): HealthGet200Response {
    return HealthGet200ResponseToJSONTyped(json, false);
}

export function HealthGet200ResponseToJSONTyped(value?: HealthGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'version': value['version'],
    };
}

