/* tslint:disable */
/* eslint-disable */
/**
 * Token Metadata Gateway
 * Token metadata lookup by chain (CAIP-2) and contract address. Caches in KV on first lookup. Sources: CoinGecko API → on-chain ERC20 eth_call → Trust Wallet assets for logo. Logo images served via gateway proxy (no external CDN access needed).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenMeta
 */
export interface TokenMeta {
    /**
     * 
     * @type {string}
     * @memberof TokenMeta
     */
    chain?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenMeta
     */
    contractAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenMeta
     */
    symbol?: string;
    /**
     * 
     * @type {number}
     * @memberof TokenMeta
     */
    decimals?: number;
    /**
     * 
     * @type {string}
     * @memberof TokenMeta
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TokenMeta
     */
    logo?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TokenMeta
     */
    updatedAt?: number;
}

/**
 * Check if a given object implements the TokenMeta interface.
 */
export function instanceOfTokenMeta(value: object): value is TokenMeta {
    return true;
}

export function TokenMetaFromJSON(json: any): TokenMeta {
    return TokenMetaFromJSONTyped(json, false);
}

export function TokenMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': json['chain'] == null ? undefined : json['chain'],
        'contractAddress': json['contractAddress'] == null ? undefined : json['contractAddress'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'decimals': json['decimals'] == null ? undefined : json['decimals'],
        'name': json['name'] == null ? undefined : json['name'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function TokenMetaToJSON(json: any): TokenMeta {
    return TokenMetaToJSONTyped(json, false);
}

export function TokenMetaToJSONTyped(value?: TokenMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': value['chain'],
        'contractAddress': value['contractAddress'],
        'symbol': value['symbol'],
        'decimals': value['decimals'],
        'name': value['name'],
        'logo': value['logo'],
        'updatedAt': value['updatedAt'],
    };
}

